title: 'MIAMI SMART REAL ESTATE                                                  Stephane Filliatreau, PA'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5463744
  brandStrength: 0.8482293
  lightness: 0.7023609
  brandColors:
    - '#FBFBFA'
    - '#88B4D0'
    - '#4B4C5B'
    - '#F36789'
    - '#F5BB1A'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'MIAMI SMART REAL ESTATE.                     Stephane Filliatreau, PA'
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8111299
layout_spectrum: 0.1728499
