name: Miami Smart Real Estate
favicon: null
layout_spectrum: 0.74808
typography_spectrum: 0.7532
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'MIAMI SMART REAL ESTATE BY Stephane Filliatreau, PA - Realtor - Global Luxury Realty'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f2531'
    - '#88b8dd'
    - '#f0f0ef'
    - '#0a7325'
    - '#d72338'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
