name: Miami Smart Real Estate
favicon: null
layout_spectrum: 0.9824435641057789
typography_spectrum: 0.17906053271144629
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffe'
    - '#1e1c1c'
    - '#c6b69d'
    - '#827360'
    - '#eadcc6'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
