name: Miami Smart Real Estate
favicon: null
layout_spectrum: 0.64599
typography_spectrum: 0.8652882
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060006'
    - '#dcdcdc'
    - '#484448'
    - '#a8a7a8'
    - '#7b787b'
  brandStrength: 0.8997494
  lightness: 0.7274436
  saturation: 0.6196742
  rhythmicContrast: 0.325188
purpose: []
